apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion-factor
  name: currency-conversion-factor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion-factor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion-factor
    spec:
      containers:
      - image: ragabms/currency-conversion-factor:k82
        imagePullPolicy: IfNotPresent
        name: currency-conversion-factor
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion-factor
  name: currency-conversion-factor
  namespace: default
spec:
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: currency-conversion-factor
  sessionAffinity: None
  type: LoadBalancer
